# Day 26 – Deep Learning with PyTorch & Hugging Face

In [ ]:

%pip install torch transformers

## PyTorch Basics

In [3]:

import torch

x = torch.tensor([
    [1.0, 2.0], 
    [3.0, 4.0],
    [5.0, 6.0]
]) # 2 rows/2 elements per row
print(x)
print(x.shape)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


## Simple Neural Network

In [4]:

import torch.nn as nn

model = nn.Linear(2,1)
print(model)


Linear(in_features=2, out_features=1, bias=True)


## Training Loop Example

In [21]:

import torch.optim as optim

X = torch.tensor([[1.0,2.0],[2.0,3.0]])
y = torch.tensor([[1.0],[0.0]])

model = nn.Linear(2,1)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

for epoch in range(2000):
    outputs = model(X)
    print(outputs)
    loss = loss_fn(outputs, y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch}, Loss {loss.item()}")


tensor([[-1.6655],
        [-2.6352]], grad_fn=<AddmmBackward0>)
Epoch 0, Loss 7.024601936340332
tensor([[-1.2684],
        [-2.0264]], grad_fn=<AddmmBackward0>)
Epoch 1, Loss 4.625923156738281
tensor([[-0.9499],
        [-1.5386]], grad_fn=<AddmmBackward0>)
Epoch 2, Loss 3.0846199989318848
tensor([[-0.6944],
        [-1.1477]], grad_fn=<AddmmBackward0>)
Epoch 3, Loss 2.0941147804260254
tensor([[-0.4895],
        [-0.8345]], grad_fn=<AddmmBackward0>)
Epoch 4, Loss 1.457453727722168
tensor([[-0.3250],
        [-0.5836]], grad_fn=<AddmmBackward0>)
Epoch 5, Loss 1.0481112003326416
tensor([[-0.1930],
        [-0.3827]], grad_fn=<AddmmBackward0>)
Epoch 6, Loss 0.7848032712936401
tensor([[-0.0870],
        [-0.2217]], grad_fn=<AddmmBackward0>)
Epoch 7, Loss 0.6153119802474976
tensor([[-0.0018],
        [-0.0929]], grad_fn=<AddmmBackward0>)
Epoch 8, Loss 0.5060917139053345
tensor([[0.0667],
        [0.0103]], grad_fn=<AddmmBackward0>)
Epoch 9, Loss 0.4355916678905487
tensor([[0.1218],
       

## Hugging Face Pipeline (Sentiment Analysis)

In [15]:

from transformers import pipeline

classifier = pipeline("sentiment-analysis")
print(classifier("I like learning AI"))


No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.


Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

[{'label': 'POSITIVE', 'score': 0.9969272017478943}]


## Generate Embeddings
### generates multiple input patterns

In [19]:

from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model = AutoModel.from_pretrained("distilbert-base-uncased")

inputs = tokenizer("Deep learning is powerful!!!", return_tensors="pt")
outputs = model(**inputs)

embeddings = outputs.last_hidden_state
print(embeddings.shape)
print(embeddings)


Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  | 
------------------------+------------+--+-
vocab_layer_norm.weight | UNEXPECTED |  | 
vocab_layer_norm.bias   | UNEXPECTED |  | 
vocab_transform.weight  | UNEXPECTED |  | 
vocab_projector.bias    | UNEXPECTED |  | 
vocab_transform.bias    | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


torch.Size([1, 9, 768])
tensor([[[-0.0797, -0.0568, -0.0435,  ..., -0.0337,  0.2208,  0.3053],
         [-0.1401,  0.0598,  0.0321,  ..., -0.0653,  0.3336,  0.1573],
         [-0.1897,  0.1068,  0.1015,  ..., -0.1523,  0.2829, -0.3699],
         ...,
         [ 0.2829,  0.0268,  0.7146,  ...,  0.0259, -0.1620, -0.1955],
         [-0.0046, -0.2089,  0.3093,  ...,  0.1072, -0.1199, -0.0981],
         [ 1.0365,  0.2209, -0.3488,  ...,  0.2321, -0.7369, -0.1344]]],
       grad_fn=<NativeLayerNormBackward0>)
